#!/usr/bin/env ruby
# frozen_string_literal: true

require "optparse"
require "pathname"
require "yaml"

options = {
  template: Pathname.new(__dir__).join("..", "deploy", "aws", "scene-staging-storage.yaml").cleanpath
}

OptionParser.new do |parser|
  parser.banner = "Usage: scene_aws_validate.rb [--template PATH]"
  parser.on("--template PATH", String, "CloudFormation template to validate") do |path|
    options[:template] = Pathname.new(path)
  end
end.parse!

errors = []

check = lambda do |condition, message|
  errors << message unless condition
end

begin
  template = YAML.safe_load(
    options[:template].read,
    permitted_classes: [],
    permitted_symbols: [],
    aliases: false
  )
rescue Errno::ENOENT, Psych::SyntaxError => e
  warn "ERROR: #{e.message}"
  exit 1
end

unless template.is_a?(Hash)
  warn "ERROR: template root must be a mapping"
  exit 1
end

metadata = template.fetch("Metadata", {}).fetch("Scene", {})
check.call(metadata["StackName"] == "scene-staging-storage", "metadata stack name must be scene-staging-storage")
check.call(metadata["Region"] == "eu-central-1", "metadata region must be eu-central-1")

parameters = template.fetch("Parameters", {})
check.call(parameters.dig("DynamoDBTableName", "Default") == "scene-staging", "table parameter must default to scene-staging")
check.call(parameters.dig("DeploymentEnvironment", "Default") == "staging", "environment must default to staging")
check.call(parameters.dig("ArtifactRootPrefix", "Default") == "scene", "artifact prefix must default to scene")

resources = template.fetch("Resources", {})
table = resources.fetch("SceneTable", {})
table_properties = table.fetch("Properties", {})
check.call(table["Type"] == "AWS::DynamoDB::Table", "SceneTable must be AWS::DynamoDB::Table")
check.call(table["DeletionPolicy"] == "Retain", "SceneTable must retain data on stack deletion")
check.call(table["UpdateReplacePolicy"] == "Retain", "SceneTable must retain data on replacement")
check.call(table_properties["BillingMode"] == "PAY_PER_REQUEST", "SceneTable must use on-demand billing")
check.call(table_properties["DeletionProtectionEnabled"] == true, "SceneTable deletion protection must be enabled")
check.call(table_properties.dig("PointInTimeRecoverySpecification", "PointInTimeRecoveryEnabled") == true, "SceneTable PITR must be enabled")
check.call(table_properties.dig("SSESpecification", "SSEEnabled") == true, "SceneTable encryption must be enabled")

expected_attributes = %w[pk sk gsi1pk gsi1sk gsi2pk gsi2sk gsi3pk gsi3sk]
attributes = Array(table_properties["AttributeDefinitions"]).to_h do |definition|
  [definition["AttributeName"], definition["AttributeType"]]
end
check.call(attributes.keys.sort == expected_attributes.sort, "SceneTable must define pk/sk and all gsi1/gsi2/gsi3 key attributes")
check.call(attributes.values.all? { |type| type == "S" }, "all table and index key attributes must be strings")

primary_key = Array(table_properties["KeySchema"]).to_h do |definition|
  [definition["AttributeName"], definition["KeyType"]]
end
check.call(primary_key == { "pk" => "HASH", "sk" => "RANGE" }, "SceneTable primary key must be pk HASH and sk RANGE")

expected_indexes = {
  "gsi1" => { "gsi1pk" => "HASH", "gsi1sk" => "RANGE" },
  "gsi2" => { "gsi2pk" => "HASH", "gsi2sk" => "RANGE" },
  "gsi3" => { "gsi3pk" => "HASH", "gsi3sk" => "RANGE" }
}
indexes = Array(table_properties["GlobalSecondaryIndexes"]).to_h do |index|
  key_schema = Array(index["KeySchema"]).to_h do |definition|
    [definition["AttributeName"], definition["KeyType"]]
  end
  [index["IndexName"], { "keys" => key_schema, "projection" => index.dig("Projection", "ProjectionType") }]
end
check.call(indexes.keys.sort == expected_indexes.keys.sort, "SceneTable must define exactly gsi1, gsi2, and gsi3")
expected_indexes.each do |name, key_schema|
  check.call(indexes.dig(name, "keys") == key_schema, "#{name} has the wrong key schema")
  check.call(indexes.dig(name, "projection") == "ALL", "#{name} must project ALL attributes")
end

bucket = resources.fetch("SceneArtifactBucket", {})
bucket_properties = bucket.fetch("Properties", {})
check.call(bucket["Type"] == "AWS::S3::Bucket", "SceneArtifactBucket must be AWS::S3::Bucket")
check.call(bucket["DeletionPolicy"] == "Retain", "SceneArtifactBucket must retain data on stack deletion")
check.call(bucket["UpdateReplacePolicy"] == "Retain", "SceneArtifactBucket must retain data on replacement")
check.call(!bucket_properties.key?("BucketName"), "artifact bucket name must be generated by CloudFormation")
check.call(bucket_properties.dig("VersioningConfiguration", "Status") == "Enabled", "artifact bucket versioning must be enabled")
check.call(bucket_properties.dig("OwnershipControls", "Rules", 0, "ObjectOwnership") == "BucketOwnerEnforced", "artifact bucket must enforce bucket-owner ownership")
public_block = bucket_properties.fetch("PublicAccessBlockConfiguration", {})
%w[BlockPublicAcls BlockPublicPolicy IgnorePublicAcls RestrictPublicBuckets].each do |setting|
  check.call(public_block[setting] == true, "artifact bucket #{setting} must be true")
end
encryption_rules = bucket_properties.dig("BucketEncryption", "ServerSideEncryptionConfiguration")
algorithms = Array(encryption_rules).map { |rule| rule.dig("ServerSideEncryptionByDefault", "SSEAlgorithm") }
check.call(algorithms.include?("AES256") || algorithms.include?("aws:kms"), "artifact bucket default encryption must be enabled")

bucket_policy = resources.fetch("SceneArtifactBucketPolicy", {})
check.call(bucket_policy["Type"] == "AWS::S3::BucketPolicy", "SceneArtifactBucketPolicy must be AWS::S3::BucketPolicy")
check.call(bucket_policy["DeletionPolicy"] == "Retain", "artifact bucket policy must survive stack deletion with the retained bucket")
check.call(bucket_policy["UpdateReplacePolicy"] == "Retain", "artifact bucket policy must survive replacement with the retained bucket")
check.call(bucket_policy.dig("Properties", "Bucket") == { "Ref" => "SceneArtifactBucket" }, "artifact bucket policy must attach only to SceneArtifactBucket")
bucket_policy_statements = Array(bucket_policy.dig("Properties", "PolicyDocument", "Statement"))
bucket_policy_sids = bucket_policy_statements.map { |statement| statement["Sid"] }
check.call(bucket_policy_sids.sort == %w[DenyInsecureTransport DenyOutdatedTls].sort, "artifact bucket policy must contain only the transport deny statements")
expected_bucket_policy_resources = [
  { "Fn::GetAtt" => ["SceneArtifactBucket", "Arn"] },
  { "Fn::Sub" => "${SceneArtifactBucket.Arn}/*" }
]
bucket_policy_statements.each do |statement|
  sid = statement["Sid"] || "unnamed"
  check.call(statement["Effect"] == "Deny", "artifact bucket policy #{sid} must be a Deny")
  check.call(statement["Principal"] == "*", "artifact bucket policy #{sid} must protect every principal")
  check.call(statement["Action"] == "s3:*", "artifact bucket policy #{sid} must cover all S3 operations")
  check.call(Array(statement["Resource"]) == expected_bucket_policy_resources, "artifact bucket policy #{sid} must cover only the bucket and its objects")
end
secure_transport_deny = bucket_policy_statements.find { |statement| statement["Sid"] == "DenyInsecureTransport" } || {}
check.call(secure_transport_deny.dig("Condition", "Bool", "aws:SecureTransport") == "false", "artifact bucket policy must deny insecure transport")
old_tls_deny = bucket_policy_statements.find { |statement| statement["Sid"] == "DenyOutdatedTls" } || {}
check.call(old_tls_deny.dig("Condition", "NumericLessThan", "s3:TlsVersion") == "1.2", "artifact bucket policy must deny TLS versions below 1.2")

access_key_resources = resources.values.select { |resource| resource["Type"] == "AWS::IAM::AccessKey" }
check.call(access_key_resources.empty?, "template must not create an IAM access key")
user = resources.fetch("SceneApplicationUser", {})
check.call(user["Type"] == "AWS::IAM::User", "SceneApplicationUser must be an IAM user")
check.call(!user.fetch("Properties", {}).key?("LoginProfile"), "application IAM user must not have a console login")

managed_policy = resources.fetch("SceneApplicationPolicy", {})
check.call(managed_policy["Type"] == "AWS::IAM::ManagedPolicy", "SceneApplicationPolicy must be a managed policy")
policy_properties = managed_policy.fetch("Properties", {})
check.call(policy_properties["Users"] == [{ "Ref" => "SceneApplicationUser" }], "application policy must attach only to SceneApplicationUser")
check.call(!policy_properties.key?("Groups") && !policy_properties.key?("Roles"), "application policy must not attach to groups or roles")
policy_statements = Array(policy_properties.dig("PolicyDocument", "Statement"))
allow_statements = policy_statements.select { |statement| statement["Effect"] == "Allow" }
check.call(policy_statements.length == allow_statements.length, "application policy must contain only explicit Allow statements")
check.call(allow_statements.map { |statement| statement["Sid"] }.sort == %w[DynamoDBTableData S3ArtifactObjects S3ArtifactVersionListing S3BucketLocation].sort, "application policy must contain exactly the four expected statements")
actions = allow_statements.flat_map { |statement| Array(statement["Action"]) }
resources_used = allow_statements.flat_map { |statement| Array(statement["Resource"]) }
check.call(actions.none? { |action| action == "*" || action.end_with?(":*") }, "application policy must not contain wildcard actions")
check.call(resources_used.none? { |resource| resource == "*" }, "application policy must not contain wildcard resources")
expected_dynamodb_actions = %w[
  dynamodb:BatchGetItem
  dynamodb:BatchWriteItem
  dynamodb:ConditionCheckItem
  dynamodb:DeleteItem
  dynamodb:DescribeTable
  dynamodb:GetItem
  dynamodb:PutItem
  dynamodb:Query
  dynamodb:TransactGetItems
  dynamodb:TransactWriteItems
  dynamodb:UpdateItem
]
dynamodb_statement = allow_statements.find { |statement| statement["Sid"] == "DynamoDBTableData" } || {}
check.call(Array(dynamodb_statement["Action"]).sort == expected_dynamodb_actions.sort, "DynamoDB permissions must match the storage backend allow-list exactly")
check.call(
  Array(dynamodb_statement["Resource"]) == [
    { "Fn::GetAtt" => ["SceneTable", "Arn"] },
    { "Fn::Sub" => "${SceneTable.Arn}/index/*" }
  ],
  "DynamoDB permissions must be limited to the SCENE table and its indexes"
)
bucket_location_statement = allow_statements.find { |statement| statement["Sid"] == "S3BucketLocation" } || {}
check.call(Array(bucket_location_statement["Action"]) == ["s3:GetBucketLocation"], "bucket-level permissions must contain only s3:GetBucketLocation")
check.call(Array(bucket_location_statement["Resource"]) == [{ "Fn::GetAtt" => ["SceneArtifactBucket", "Arn"] }], "bucket-level permissions must be limited to SceneArtifactBucket")
version_listing_statement = allow_statements.find { |statement| statement["Sid"] == "S3ArtifactVersionListing" } || {}
check.call(Array(version_listing_statement["Action"]) == ["s3:ListBucketVersions"], "version listing permissions must contain only s3:ListBucketVersions")
check.call(Array(version_listing_statement["Resource"]) == [{ "Fn::GetAtt" => ["SceneArtifactBucket", "Arn"] }], "version listing must be limited to SceneArtifactBucket")
check.call(
  version_listing_statement.dig("Condition", "StringLike", "s3:prefix") == [
    { "Fn::Sub" => "${ArtifactRootPrefix}/${DeploymentEnvironment}/*" }
  ],
  "version listing must be limited to the SCENE environment prefix"
)
object_statement = allow_statements.find { |statement| statement["Sid"] == "S3ArtifactObjects" } || {}
expected_object_actions = %w[
  s3:AbortMultipartUpload
  s3:DeleteObject
  s3:DeleteObjectVersion
  s3:GetObject
  s3:GetObjectVersion
  s3:ListMultipartUploadParts
  s3:PutObject
]
check.call(Array(object_statement["Action"]).sort == expected_object_actions.sort, "S3 object permissions must match the artifact backend allow-list exactly")
expected_object_resource = "${SceneArtifactBucket.Arn}/${ArtifactRootPrefix}/${DeploymentEnvironment}/*"
check.call(
  Array(object_statement["Resource"]) == [{ "Fn::Sub" => expected_object_resource }],
  "application object permissions must be limited to the SCENE environment prefix"
)

expected_outputs = %w[
  ApplicationPolicyArn
  ApplicationUserArn
  ApplicationUserName
  ArtifactBucketArn
  ArtifactBucketName
  ArtifactRootPrefix
  DynamoDBTableArn
  DynamoDBTableName
]
check.call(template.fetch("Outputs", {}).keys.sort == expected_outputs.sort, "template outputs must contain only the expected non-secret values")

if errors.empty?
  puts "OK: #{options[:template]} parsed and passed #{expected_indexes.length}-GSI storage/IAM checks"
  exit 0
end

errors.each { |error| warn "ERROR: #{error}" }
warn "FAILED: #{errors.length} validation error#{errors.length == 1 ? '' : 's'}"
exit 1
